### PR TITLE
Merge pull request #1 from GDES-Web/main

### PR DESCRIPTION
**Pull request by andreashep**
Feedback

### CODE REVIEW

**Comment by kristinardis** [comment]
At least I'm getting modifications now.  I clicked
on the tab to get them.
________________________________

**Comment by andreashep** [comment]
For some reason this file won't let me add myself as a reviewer.  So I was not able to review these files.

**Comment by andreashep** [comment]
Yay!  For some weird reason it won't let me add myself as a reviewer to your assignment.   That's where i was getting so confused.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kristinardis** [comment]
Try this:  Go to github.com/GDES-Web
click on repositories at the top
click on my name, kristinardis
under "code" is a tab that probably says "main" and there is a drop-down to "feedback"
but it could say "feedback" with a drop down to "main"
click on "feedback"
click on a file of mine that you want to comment on
I'm not sure where you would go from there as I am doing that in my account....
________________________________

**Pull request closed without merging**
